# Generated by Django 5.0.6 on 2024-07-04 15:33

import edu_center.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_center', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=edu_center.helpers.Save_image.save_image),
        ),
    ]
