# Generated by Django 5.0.6 on 2024-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_center', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
